create table reviews
(id bigint generated by default as identity,
 posted_by varchar(255),
 message varchar(3000),
 time_stamp bigint,
 book_id bigint,
  primary key (id),
  CONSTRAINT fk_book_reviews FOREIGN KEY(book_id) references books(id))