create table orders
(id bigint generated by default as identity,
 address_line_no_one varchar(3000) not null,
 address_line_no_two varchar(3000) not null,
 address_city varchar(500) not null,
 address_state varchar(500) not null,
 address_pin_code varchar(100) not null,
 address_country varchar(100) not null,
 user_email_id varchar(100) not null,
 book_id bigint not null,
 no_of_copies int not null,
 payment_method varchar(100) not null,
 total_price numeric not null,
 primary key (id)
 )
